parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: '${{ parameters.name }} build and test'
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        debug-build:
          BUILD_CONFIG: Debug
        release-build:
          BUILD_CONFIG: Release
    steps:
      # .NET Core 3 SDK is pre-installed
      #- task: UseDotNet@2
      #  displayName: 'Use dotnet sdk 3.x'
      #  inputs:
      #    version: $(SDK_VERSION)
      #    includePreviewVersions: true

      - bash: |
          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"
          echo 'environment variables:'
          env | sort
          
          chmod u+x ./build.sh
        displayName: init

      - bash: ./build.sh build
        displayName: build

      - bash: ./build.sh test-coverage
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'

      - bash: |
            cd tests/Coverage

            workDir="$(System.DefaultWorkingDirectory)"

            if [[ "$AGENT_OS" == "Windows_NT" ]]; then
                # Windows needs special treetment for the substitution due the \
                workDir="${workDir//\\/\\\\}\\\\"
            else
                workDir+="/"
            fi

            # Mac has a different sed, so special case it (hooray for standars ;-))
            if [[ "$AGENT_OS" != "Darwin" ]]; then
                sed -i 's|<source>[^<]*</source>|<source>/</source>|g' "Cobertura.xml"
                sed -i "s|${workDir}||g" "Cobertura.xml"
            else
                sed -i '' 's|<source>[^<]+</source>|<source>/</source>|g' "Cobertura.xml"
                sed -i '' "s|${workDir}||g" "Cobertura.xml"
            fi
        displayName: make Cobertura-paths relative

      # shortcut for PublishPipelineArtifact
      # Coverage report will be created later in a different stage
      - publish: tests/Coverage/Cobertura.xml
        artifact: 'Coverage-${{ parameters.name }}-$(BUILD_CONFIG)'

      - bash: ./build.sh pack
        displayName: pack
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['BUILD_CONFIG'], 'Release'))

      - publish: 'NuGet-Packed'
        artifact: 'NuGet-Packed'
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['BUILD_CONFIG'], 'Release'), ne(variables['Build.Reason'], 'PullRequest'))
