jobs:
  - job: docs_build
    pool:
      vmImage: 'windows-2019'
    steps:
      - bash: |
          export PATH="$(pwd)/dotnet:$PATH"
          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"

          chmod u+x ./build.sh
          ./build.sh build
        displayName: build

      - powershell: |
          choco install docfx -y

          if ($lastexitcode -ne 0) {
              throw ("Error generating document")
          }
        displayName: 'install docfx'

      - powershell: |
          cd api-doc
          docfx

          if ($lastexitcode -ne 0) {
              throw ("Error generating document")
          }
        displayName: 'docfx build'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'api-doc/_site'
          artifactName: 'docs'
